module.exports=class {
    id;
    title;
    author;
    description;
    genre;
    coverImage;
    rating;
    reviews;
    publishedYear;
    availabesCopies;
    createdBy;
    createdAt
    constructor(model){
        this.id=model.id;
        this.title=model.title;
        this.author=model.author;
        this.description=model.description;
        this.genre=model.genre;
        this.coverImage=model.coverImage;
        this.rating=model.rating;
        this.reviews=model.reviews;
        this.publishedYear=model.publishedYear;
        this.availabesCopies=model.availabesCopies;
        this.createdBy=model.createdBy;
        this.createdAt=model.createdAt;
    }
}